[http]
address = "localhost"
port = 8000
# worker-threads = (cpu-count * 2)
# key-file = (none)
web-root = "/usr/share/voctra/www"
rocket-env = "production"

[database]
url = "/var/lib/voctra/voctra.sqlite"
pool-size = 10
# min-idle = (pool-size)
helper-threads = 3
test-on-checkout = true
initialization-fail-fast = true
idle-timeout = 600
max-lifetime = 1800
connection-timeout = 30

[daemon]
pid-file = "/run/voctra.pid"
cwd = "/"
umask = 23 # 027
user = "voctra"
# group = (user-primary-group)
stop-timeout = 5

[logging.appenders.main]
kind = "file"
path = "/var/log/voctra/voctra.log"
encoder = { kind = "pattern", pattern = "{d} {l} {t} - {m}{n}" }

[logging.appenders.rocket]
kind = "file"
path = "/var/log/voctra/rocket.log"
encoder = { kind = "pattern", pattern = "{d} {l} {t} - {m}{n}" }

[logging.root]
level = "info"
appenders = ["main"]

[logging.loggers.rocket]
level = "info"
appenders = ["rocket"]
additive = false

[logging.loggers._]
level = "info"
appenders = ["rocket"]
additive = false
