#!/bin/sh

set -e

case "$1" in
    configure)
        adduser --quiet --system --no-create-home --home /var/lib/voctra voctra
        chown voctra: /var/lib/voctra/
        chown voctra:adm /var/log/voctra/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
